stages:
  gen_data:
    cmd: python3 src/gen/batch.py
    outs:
      - data/single_block_v2.h5:
          cache: false

  train:
    foreach: ${train.loss_functions}
    do:
      cmd: python3 src/train.py ${item}
      deps:
        - data/single_block_v2.h5
        - src/train.py
        - src/training/engine.py
        - src/data/dataset.py
      params:
        - train.max_epochs
        - train.device
        - train.lr
        - train.confidence
        - train.noise
        - train.loss_functions
      outs:
        - checkpoints/${item}_final.pt:
            cache: false
        - checkpoints/${item}_best.pt:
            cache: false

  eval:
    foreach: ${train.loss_functions}
    do:
      cmd: python3 src/eval.py ${item} --headless
      deps:
        - checkpoints/${item}_final.pt
        - src/eval.py
        - src/training/evaluation.py
      params:
        - train.components
        - train.confidence
        - train.noise
        - train.loss_functions
        - eval.output_dir
        - eval.threshold
      metrics:
        - metrics/eval_${item}.json:
            cache: false
